# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dc4c0602bd08407e6b90e341445bb313f90a7bdf39c949465e71ba291bac300039a2bdf4e7cbaf42e9c21f9677e2740e855819e38bdda7c4a14a8fc0601a7ed

test:
  secret_key_base: 5987287ff01738542358b2764af8669c58881ad6312f4f8d3dceae7483d8be66baff31166c04c843db6376d2457f962c3c08caf4f9024593d4a2aa5196cc6f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
